language: python
matrix:
    include:
        - os: linux
          python: 3.6
          env: TOXENV=py36
          install:
            - "pip install -r requirements.txt"
        - os: osx
          language: generic
          python: 3.6
          env: TOXENV=py36
          install:
            - "pip install --user -r requirements.txt"
before_script:
  - "python3 -m nltk.downloader punkt"
  - "python3 -m nltk.downloader wordnet"
  - "python3 -m nltk.downloader stopwords"
script: make test
env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/matchzoo
after_success:
      - codecov